networks:
  traefik-network:
    external: true
  nextcloud-internal:
    internal: true

volumes:
  nextcloud_html:
  db_data:
  redis_data:

secrets:
  mariadb_root_password:
    external: true
  mariadb_user_password:
    external: true
  redis_password:
    external: true

services:
  mariadb:
    image: mariadb:11.4
    networks:
      - nextcloud-internal
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: admin
      MYSQL_PASSWORD_FILE: /run/secrets/mariadb_user_password
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - mariadb_root_password
      - mariadb_user_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.storage == primary

  redis:
    image: redis:7
    networks:
      - nextcloud-internal
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    secrets:
      - redis_password
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.storage == primary

  nextcloud:
    image: nextcloud:32.0.1-apache
    networks:
      - traefik-public
      - nextcloud-internal
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: admin
      MYSQL_PASSWORD_FILE: /run/secrets/mariadb_user_password
      REDIS_HOST: redis
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      OVERWRITEPROTOCOL: https
      OVERWRITEHOST: nextcloud.domain.com
    secrets:
      - mariadb_user_password
      - redis_password
    volumes:
      - nextcloud_html:/var/www/html
    deploy:
      placement:
        constraints:
          - node.labels.storage == primary
      replicas: 1

  nextcloud-cron:
    image: nextcloud:32.0.1-apache
    entrypoint: /cron.sh
    secrets:
      - mariadb_user_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.storage == primary
    networks:
      - internal
    volumes:
      - nextcloud_html:/var/www/html
